[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pointwisepy"
version = "1.0.1"
dependencies = [
    "pointwise-glyph-client",
]

[project.urls]
"Homepage" = "https://github.com/bex-d/pointwisepy"